steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        uvicorn main:app --host=0.0.0.0 --port=8080

timeout: 900s
